theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://zenodo.org/record/4495606/files/DeepAccessTransfer.zip?download=1
  tar_url: https://zenodo.org/record/4495606/files/DeepAccessTransfer.tar.gz?download=1
  quickstart: ./quickstart.md
  train: ./train.md
  interpret: ./interpret.md