[build-system]
requires = [
	 "numpy>=1.20.2",
	 "keras>=2.4.3",
	 "tensorflow>=2.4.1",
	 "scikit-learn>=0.24.1",
	 "scipy>=1.6.2",
	 "matplotlib>=3.4.1",
	 "setuptools>=42",	
         "wheel"
]
build-backend = "setuptools.build_meta"